version: '3'


services:


  app:
    build:
      context: .
      dockerfile: Dockerfile_flask
    hostname: app
    restart: unless-stopped

    container_name: flaskapp
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: mongodb
      MONGODB_HOSTNAME: mongodb
      FLASK_ENV: development
    ports:
     - "5000:5000"
    command: ["pipenv", "run", "python", "run.py"]
    volumes:
      - ./app:/home/dev/code/app*
    links:
      - mongodb
      - scraper



  mongodb:
    image: mongo:4.0.8
    hostname: mongodb
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
        - "27017:27017"


  scraper:

    build:
      context: .
      dockerfile: Dockerfile_scraper
    hostname: scraper
    container_name: scraper
    restart: always

    ports:
    - "9080:9080"
    volumes:
    - ./Scraper:/scrapyrt/project

    links:
      - mongodb


networks:
  default:

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
